# Generated by Django 6.1 on 2026-08-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='current_floor',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
