# Generated by Django 6.1 on 2026-08-28 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_alter_dev_current_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamCone',
            fields=[
                ('icecream_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ice_cream.icecream')),
            ],
            options={
                'abstract': False,
            },
            bases=('ice_cream.icecream',),
        ),
        migrations.CreateModel(
            name='IceCreamPrism',
            fields=[
                ('icecream_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ice_cream.icecream')),
            ],
            options={
                'abstract': False,
            },
            bases=('ice_cream.icecream',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=15)),
                ('notification_settings', models.BooleanField(default=False)),
                ('current_floor', models.IntegerField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='IceCreamMan',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='_brand',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='_flavor',
        ),
        migrations.AddField(
            model_name='fridge',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecream',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecream',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecream',
            name='width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ice_cream.person'),
        ),
        migrations.DeleteModel(
            name='Dev',
        ),
    ]
